spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: boot-starter

server:
  port: 8098
#  servlet:
#    context-path: /lyoyang
#logging:
#  path: classpath:logback-boot.xml
stu:
  name: jim
  age: 23
debug: true
