spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: boot-starter

server:
  port: 8088
