version: '3.8'

services:
  redis:
    image: "redis:v1"
    ports:
      - "6379:6379"
    networks:
      - legacy

  boot-redis:
    build: .
    ports:
      - "8080:8080"
    command: java -jar app.jar
    volumes:
      - type: volume
        source: counter-vol
        target: /code
    networks:
      - legacy
    environment:
      REDIS_HOST: redis
volumes:
  counter-vol:

networks:
  legacy: