spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2
    username: root
    password: root
  devtools:
    livereload:
      enabled: true
  redis:
    host: localhost
  cache:
    type: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: warn
    com.lyoyang.cache.dao: debug
debug: true