server:
  port: 8080
  servlet:
    context-path: /lyoyang
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  redis:
#    数据库索引
    database: 6
    host: 192.168.101.13
    port: 6379
    jedis:
      pool:
#      连接池最大连接数 负值表示没有限制
        max-active: -1
#        连接池最大阻塞等待时间
        max-wait: -1
#        连接池最大空闲连接
        max-idle: 8
#        连接池最小空闲连接
        min-idle: 1
#        连接超时时间(毫秒)
    timeout: 6000
    password: ipaynow
#logging:
#  level:
#    com.lyoyang.springbootredis.dao: trace
#  config: classpath:logback-boot.xml

